rewrite fuk(

diff --git a/2fash b/2fash
--- a/2fash
+++ b/2fash
@@ -1,49 +1,177 @@
 #!/usr/bin/env bash
 
-source head.sh
-source format.sh
-source tools.sh
+FASH_COMMAND="2fash"
 
-check_deps
+[[ -z "$FASH_DIRECTORY" ]] && FASH_DIRECTORY="$HOME/.2fash"
+[[ -z "$FASH_DIRECTORY_BIN" ]] && FASH_DIRECTORY_BIN="$FASH_DIRECTORY/bin"
+[[ -z "$FASH_DIRECTORY_ACCOUNTS" ]] && FASH_DIRECTORY_ACCOUNTS="$FASH_DIRECTORY/accounts"
 
-command=$1
 
-print_help() {
-	print_help_usage_head "${FASH_COMMAND} [COMMAND] ${FORMAT_LYELLOW}?${FORMAT_NORM}[ACCOUNT] [OPTION]..."
-	echo ""
-	print_help_head "COMMANDS"
-	print_help_command "help,\th" "show help"
-	print_help_command "init,\ti" "add a new account"
-	print_help_command "code,\tc" "get 2fa code for account"
-	print_help_command "list,\tls" "print accounts"
-	print_help_command "remove,\trm" "remove account"
-	print_help_command "uninstall" "uninstall 2fash"
+# --- FORMAT ---
+FORMAT_DEFAULT="\e[39m"
+FORMAT_NORM="\e[0m"
+FORMAT_BOLD="\e[1m"
+FORMAT_DIM="\e[2m"
+FORMAT_UNDERLINE="\e[4m"
+FORMAT_BLINK="\e[5m"
+FORMAT_INV="\e[7m"
+
+FORMAT_RED="\e[31m"
+FORMAT_LRED="\e[91m"
+
+FORMAT_GREEN="\e[32m"
+FORMAT_LGREEN="\e[92m"
+
+FORMAT_GREEN="\e[32m"
+FORMAT_LGREEN="\e[92m"
+
+FORMAT_BLACK="\e[30m"
+FORMAT_WHITE="\e[97m"
+FORMAT_LGRAY="\e[37m"
+FORMAT_DGRAY="\e[90m"
+
+FORMAT_YELLOW="\e[33m"
+FORMAT_LYELLOW="\e[93m"
+
+FORMAT_BLUE="\e[34m"
+FORMAT_LBLUE="\e[94m"
+
+FORMAT_MAGENTA="\e[35m"
+FORMAT_LMAGENTA="\e[95m"
+
+FORMAT_CYAN="\e[36m"
+FORMAT_LCYAN="\e[96m"
+
+__2fish_echo_error() {
+	echo -e "\n ${FORMAT_NORM}${FORMAT_RED}${FORMAT_BOLD}Error: ${FORMAT_NORM}${1}\n"
 }
 
-case ${command} in
-	[hH] | [hH][eE][lL][pP])
-		print_header
-		print_help
+__2fish_print_header() {
+	echo ""
+	echo -e "\t ____  _____ _    ____  _   _ "
+	echo -e "\t|___ \|  ___/ _  / ___|| | | |"
+	echo -e "\t  __) | |_ / _ _ \___ \| |_| |"
+	echo -e "\t / __/|  _/ ___ _ ___) |  _  |"
+	echo -e "\t|_____|_|/_/   \ _ ___/|_| |_|"
+	echo ""
+	echo ""
+}
+
+__2fish_read_text_label_bold() {
+	echo -en " ${FORMAT_NORM}${1}: ${FORMAT_BOLD}${2}"
+}
+
+__2fish_read_text_label() {
+	echo -en " ${FORMAT_NORM}${1}: ${2}${FORMAT_NORM}"
+}
+
+__2fash_print_help_usage_head() {
+	echo -e " ${FORMAT_BOLD}USAGE:${FORMAT_NORM} $@"
+}
+
+__2fash_print_help_head() {
+	echo -e " ${FORMAT_BOLD}$@:${FORMAT_NORM}"
+}
+
+__2fash_print_help_command() {
+	echo -e "\t$1 \t- $2"
+}
+# --- END FORMAT ---
+
+
+
+# --- TOOLS ---
+__2fash_check_dependencies() {
+	to_install_arch=()
+	to_install_fedora=()
+	to_install_ubuntu=()
+
+	install_deps=0
+
+	! [[ -x "$(command -v oathtool)" ]] && install_deps=1 && to_install_arch+=('oath-toolkit') && to_install_fedora+=('oathtool') && to_install_ubuntu+=('oathtool')
+	! [[ -x "$(command -v gpg)" ]] && install_deps=1 && to_install_arch+=('gpg gnupg') && to_install_fedora+=('gnupg2') && to_install_ubuntu+=('gpg gpgv2')
+
+	if [[ "$install_deps" == "1" ]]; then
+		__2fish_echo_error "install dependencies"
+		echo -e " Arch\t${FORMAT_BOLD}sudo pacman -S ${to_install_arch[@]}${FORMAT_NORM}"
+		echo -e " Fedora\t${FORMAT_BOLD}sudo dnf install ${to_install_fedora[@]}${FORMAT_NORM}"
+		echo -e " Ubuntu\t${FORMAT_BOLD}sudo apt install ${to_install_ubuntu[@]}${FORMAT_NORM}"
 		echo ""
+		exit 2
+	fi
+}
+
+__2fash_is_account_exists() {
+	[[ -d "$FASH_DIRECTORY_ACCOUNTS/$1" ]] && echo 1 || echo 0
+}
+
+__2fash_is_account_encrypted() {
+	[[ -f "$FASH_DIRECTORY_ACCOUNTS/$1/.gpgdata" ]] && echo 1 || echo 0
+}
+# --- END TOOLS ---
+
+# --- ERRORS ---
+__2fash_throw_error_if_account_doesnt_exist() {
+	[[ $(__2fash_is_account_exists "$1") == "0" ]] && __2fish_echo_error "account doesn't exist" && exit 10
+}
+
+__2fash_throw_error_if_account_exists() {
+	[[ $(__2fash_is_account_exists "$1") == "1" ]] && __2fish_echo_error "account already exist" && exit 11
+}
+
+__2fash_throw_error_if_account_secret_doesnt_exist() {
+	! [[ -f "$FASH_DIRECTORY_ACCOUNTS/$1/.secret" ]] && __2fish_echo_error "secret file doesn't exist" && exit 12
+}
+# --- END ERRORS ---
+
+
+__2fash_print_help() {
+	__2fash_print_help_usage_head "${FASH_COMMAND} [COMMAND] ${FORMAT_LYELLOW}?${FORMAT_NORM}[ACCOUNT] [OPTION]..."
+	echo ""
+	__2fash_print_help_head "COMMANDS"
+	__2fash_print_help_command "help,\th" "show help"
+	__2fash_print_help_command "init,\ti" "add a new account"
+	__2fash_print_help_command "code,\tc" "get 2fa code for account"
+	__2fash_print_help_command "list,\tls" "print accounts"
+	__2fash_print_help_command "remove,\trm" "remove account"
+	__2fash_print_help_command "uninstall" "uninstall 2fash"
+}
+
+
+# --- START LOGIC ---
+
+__2fash_check_dependencies
+
+case $1 in
+	[hH] | [hH][eE][lL][pP])
+		__2fish_print_header
+		__2fash_print_help
+		echo ""
+		shift
 	;;
 	[iI] | [iI][nN][iI][tT])
-		bash "$FASH_DIRECTORY_BIN/2fash_init.sh" -d="$FASH_DIRECTORY_ACCOUNTS" "$@"
+		source "$FASH_DIRECTORY_BIN/2fash_init.sh" -d="$FASH_DIRECTORY_ACCOUNTS" "$@"
+		shift
 	;;
 	[cC] | [cC][oO][dD][eE])
-		bash "$FASH_DIRECTORY_BIN/2fash_code.sh" -a="$2" "$@"
+		source "$FASH_DIRECTORY_BIN/2fash_code.sh" -a="$2" "$@"
+		shift
 	;;
 	[lL][sS] | [lL][iI][sS][tT])
-		bash "$FASH_DIRECTORY_BIN/2fash_list.sh" "$@"
+		source "$FASH_DIRECTORY_BIN/2fash_list.sh" "$@"
+		shift
 	;;
 	[rR][mM] | [rR][eE][mM][oO][vV][eE])
-		bash "$FASH_DIRECTORY_BIN/2fash_remove.sh" -a="$2" "$@"
+		source "$FASH_DIRECTORY_BIN/2fash_remove.sh" -a="$2" "$@"
+		shift
 	;;
 	[uU][nN][iI][nN][sS][tT][aA][lL][lL])
-		bash "$FASH_DIRECTORY_BIN/2fash_uninstall.sh" "$FASH_DIRECTORY"
+		source "$FASH_DIRECTORY_BIN/2fash_uninstall.sh"
+		shift
 	;;
 	*)
-		print_header
-		print_help
+		__2fish_print_header
+		__2fash_print_help
 		echo ""
 	;;
 esac
